apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-kxkl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-kxkl@sha256:7b150ed17cb1aaad2698a673d0f72ad19fdb3189549eba82185d1f9dc026e761
        name: my-nodejs
        resources: {}
status: {}
